import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/app/components/header";
import Main from "@/app/components/main";
import Footer from "@/app/components/footer";

const inter = Inter({ subsets: ['latin'], })

export const metadata: Metadata = {
  title: 'GizliBahçe ',
  description: 'Generated by create next app',
  authors : [{ name : "Asim RAHAL", url: 'https://www.linkedin.com/in/asimrahal/'}]

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#ded8d4]/50`}>
      <Header/>
        {children}
      <Footer />
      </body>
    </html>
  )
}
